import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
});

const cascadia = localFont({
    src: 'CascadiaCode.ttf',
    variable: '--font-cascadia',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

interface IRootLayoutProps {
    children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<IRootLayoutProps>) {
    return (
        <html lang="en">
            <body className={`${roboto.variable} ${cascadia.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
