import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import localFont from 'next/font/local';

import Footer from '@/components/layouts/footer';
import Nav from '@/components/layouts/nav';
import SectionsContextProvider from '@/components/providers/sections-context';
import ThemeContextProvider from '@/components/providers/theme-context-provider';
import ContactMe from '@/features/contact-me/components/contact-me';

import './globals.css';

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
});

const cascadia = localFont({
    src: 'CascadiaCode.ttf',
    variable: '--font-cascadia',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default function RootLayout({ children }: React.PropsWithChildren) {
    return (
        <html lang="en">
            <body className={`${roboto.variable} ${cascadia.variable} antialiased`}>
                <ThemeContextProvider>
                    <SectionsContextProvider>
                        <Nav />
                        <main>{children}</main>
                        <Footer>
                            <ContactMe />
                        </Footer>
                    </SectionsContextProvider>
                </ThemeContextProvider>
            </body>
        </html>
    );
}
